version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: pgdatabase

    networks:
      - lms_network
    ports:
      - "5432:5432"

networks:
  lms_network:
    external: true
   
