version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vite"
        versions:
          - "<4.0.0" # Ignore versions below 4.0.0 to avoid known security issues