---
version: '3.8'
services:
  time:
    build: ./
    command: yarn develop
    restart: always
    volumes:
      - "./src:/app/src"
      - "./public/tmp:/app/public/tmp"
    ports:
      - 80:3000
    networks:
      - sabayone
    environment:
      #HOST: 0.0.0.0
      PORT: 3000
      # SabayOne Url
      SABAY_ONE_URL: https://one.testing.sabay.com
      APP_KEYS: ySDQCdPoECaoy3kv/k+e5Q==,xT+zJb+VcklU7R23D+9BrQ==,TDKKr+TqqmIeJYAeLB6I5A==,bNK+4+1cniwATGMBjp6raA==
      API_TOKEN_SALT: lSl/cydQ5MBw0hXuofCgeQ==
      ADMIN_JWT_SECRET: MEKgB4Y0SPzPYOTJTFfTug==
      TRANSFER_TOKEN_SALT: XCfj/NVvZW6d/CM74A2fUg==
      # Database
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql_container
      DATABASE_PORT: 3306
      DATABASE_NAME: mydatabase
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_SSL: "false"
      JWT_SECRET: Vdts7PJ6cBSvGXSBXOKfuA==
      DATABASE_POOL_MIN: 0
      # One Signal Stg
      ONE_SIGNAL_API_KEY: OWI5M2VlYjItYjAzNy00ZDRiLTg4ZjMtY2RmNjBmNGM5MjM0
      ONE_SIGNAL_APP_ID: afd1c6f5-e78b-450c-8fa0-72efefec5690
      # Url
      BASE_URL: https://power-stone.testing.sabay.com
      #S3 Credentials
      S3_ENDPOINT: https://fsgw.sabay.com
      S3_ACCESS_KEY_ID: YVDA7KC31040BHQCZGDS
      S3_SECRET_ACCESS_KEY: HhqAbJfAXxNKHIfkufk0yGW7F4cLTAsfMeipTsSk
      S3_REGION: us-west-2
      S3_BUCKET_NAME: power-stone-stg

networks:
    sabayone:
        external: true
