version: '3.8'

services:
  app:
    image: your-app-image:latest
    container_name: library_system_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=your_user
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=library_system
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: library_system_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: library_system
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: library_system_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: