---
version: '3.8'
services:
  library:
    build: ./
    command: npm run develop
    restart: always
    volumes:
      - "./src:/app/src"
      - "./public/tmp:/app/public/tmp"
    ports:
      - 84:1337
    env_file:
      - ./.env
    networks:
      - lms_network

    environment:
      CLOUDINARY_NAME: dawhc3n9y
      CLOUDINARY_KEY: 131395386716243
      CLOUDINARY_SECRET: 42Ui4ow1Z894NwcTD58d8wuUMYM

networks:
  lms_network:
    external: true
      