name: Build Docker Image

on:
  push:
    branches:
      - master  # Or your deployment branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .
      - name: Run tests
        run: |
          docker run  ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
